apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-hbou
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-hbou
    app.kubernetes.io/part-of: integ-app-tmtn
  name: hacbs-test-project-hbou
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-hbou
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-hbou
    spec:
      containers:
      - image: quay.io/quay-or-not-to-quay/nbe-e2e-ksam-tenant/integ-app-tmtn/hacbs-test-project-hbou@sha256:0d3f693ead769fa421c962305d9b89090f732b65b9a5b0f623cbb6d990f8d75b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
